MANUAL_CONTROL = "MANUAL_CONTROL"
DRONE_OPTIONS = "DRONE_OPTIONS"
SERVER_MESSAGE = "SERVER_MESSAGE"

SYNCKEY_ROLL = "roll"
SYNCKEY_PITCH = "pitch"
SYNCKEY_THROTTLE = "throttle"
SYNCKEY_YAW = "yaw"


SYNCKEY_ARMED = "ARMED"
SYNCKEY_MODE = "MODE"
SYNCKEY_GLOBAL_LOCATION = "GLOBAL_LOCATION"