credentials:
  username: admin
  password: admin

clientJson:
  - "./from.json"

token: default
filters:
  - ior_research.utils.filterchains.RControlNetMessageFilter
streamer:
  serverPath: https://192.168.137.1/#/stream?host=192.168.137.1
  video: true
  audio: true