!RCNConfig
credentials:
  username: admin
  password: admin
clientJson:
- /ior/configs/default-connection1-slave-default-pi.json
token: default
filters:
- !RCNFilters
  name: ior_research.utils.filterchains.RControlNetMessageFilter
  configuration:
- !RCNFilters
  name: ior_research.utils.filterchains.mqtt.MQTTPublisher
  configuration:
    server: 192.168.46.131
    port: 1883
    defaultTopic: rcn.robot.drone.messages